apiVersion: v1
kind: ServiceAccount
metadata:
  name: carol
  namespace: prometheus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:  
  name: cr-pod-reader  
rules:
- apiGroups: [""] # "" означает apiGroup под именем core или legacy
  resources: ["pods"]
  verbs: ["get", "list","watch"] #"create", "update", "delete", "patch", "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-sa-ns-prometeus # под этим именем мы потом увидим этот RoleBinding
subjects:
- kind: Group # Group, ServiceAccount
  name: system:ServiceAccounts # имя чувствительно к регистру
  namespace: prometheus
roleRef:
  kind: ClusterRole # явно указываем Role или ClusterRole
  name: cr-pod-reader # а тут имя той Role или ClusterRole к которой мы биндимся
  apiGroup: rbac.authorization.k8s.io